import { defineConfig, presetUno, presetAttributify, presetIcons } from 'unocss'

export default defineConfig({
  safelist: [
    'i-carbon-menu',
    'i-carbon-chat',
    'i-carbon-sun',
    'i-carbon-rain',
    'i-carbon-rain-heavy',
    'i-carbon-rain-drizzle',
    'i-carbon-thunderstorm',
    'i-carbon-sleet',
    'i-carbon-snow',
    'i-carbon-fog',
    'i-carbon-haze',
    'i-carbon-cloudy',
    'i-carbon-partly-cloudy',
    'i-carbon-train',
    'i-carbon-train-profile',
    'i-carbon-ticket',
    'i-carbon-hotel',
    'i-carbon-restaurant',
    'i-carbon-map',
    'i-carbon-location',
    'i-carbon-location-heart',
    'i-carbon-information',
    'i-carbon-list-numbered',
    'i-carbon-workflow-automation',
    'i-carbon-notebook-reference',
    'i-carbon-reminder',
    'i-carbon-airline-passenger-care',
    'i-carbon-in-progress',
    'i-carbon-tour',
    'i-carbon-cafe',
    'i-carbon-plane',
    'i-carbon-alarm',
    'i-carbon-task',
    'i-carbon-warning-alt-filled',
    'i-carbon-checkmark-filled',
    'i-carbon-warning',
    'i-carbon-close-filled',
    'i-carbon-volume-up',
    'i-carbon-volume-mute',
    'i-carbon-microphone',
    'i-carbon-microphone-filled',
    'i-carbon-keyboard',
    'i-carbon-send',
    'i-carbon-close',
    'i-carbon-settings',
    'i-carbon-search',
    'i-carbon-chevron-down',
    'i-carbon-chevron-right',
    'i-carbon-overflow-menu-vertical',
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
  ],
  theme: {
    colors: {
      primary: '#6366f1',
      'primary-dark': '#4f46e5',
    },
  },
})
