/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentProcessPreview: typeof import('./components/chat/AgentProcessPreview.vue')['default']
    AllConversationsModal: typeof import('./components/conversations/AllConversationsModal.vue')['default']
    AvatarErrorFallback: typeof import('./components/AvatarErrorFallback.vue')['default']
    BotReplyContent: typeof import('./components/chat/BotReplyContent.vue')['default']
    CompanionCard: typeof import('./components/home/CompanionCard.vue')['default']
    CompanionHero: typeof import('./components/home/CompanionHero.vue')['default']
    CompanionProgressCard: typeof import('./components/home/CompanionProgressCard.vue')['default']
    ContentBlockRenderer: typeof import('./components/chat/ContentBlockRenderer.vue')['default']
    DesktopChatLayout: typeof import('./components/chat/DesktopChatLayout.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmotionDebugPanel: typeof import('./components/chat/EmotionDebugPanel.vue')['default']
    HealthMetricCard: typeof import('./components/chat/HealthMetricCard.vue')['default']
    HeroArtTitle: typeof import('./components/home/HeroArtTitle.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    MarkdownReply: typeof import('./components/chat/MarkdownReply.vue')['default']
    MemoryCard: typeof import('./components/home/MemoryCard.vue')['default']
    MobileChatLayout: typeof import('./components/chat/MobileChatLayout.vue')['default']
    QuickActionBubbles: typeof import('./components/chat/QuickActionBubbles.vue')['default']
    ReadSourcesDisclosure: typeof import('./components/chat/ReadSourcesDisclosure.vue')['default']
    RegisterModal: typeof import('./components/RegisterModal.vue')['default']
    RenameConversationModal: typeof import('./components/conversations/RenameConversationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./components/home/SidebarNav.vue')['default']
    SkillBundleCard: typeof import('./components/skills/SkillBundleCard.vue')['default']
    SkillCard: typeof import('./components/skills/SkillCard.vue')['default']
    SkillCenterModal: typeof import('./components/skills/SkillCenterModal.vue')['default']
    SkillPackageCard: typeof import('./components/home/SkillPackageCard.vue')['default']
    SpeechBubble: typeof import('./components/SpeechBubble.vue')['default']
    StatusDrawer: typeof import('./components/StatusDrawer.vue')['default']
    SubscriptionModal: typeof import('./components/home/SubscriptionModal.vue')['default']
    TaskProgressCard: typeof import('./components/chat/TaskProgressCard.vue')['default']
    TaskResultBlocks: typeof import('./components/chat/TaskResultBlocks.vue')['default']
    VoiceCloneModal: typeof import('./components/VoiceCloneModal.vue')['default']
    WeatherForecastCard: typeof import('./components/chat/WeatherForecastCard.vue')['default']
    WeatherMark: typeof import('./components/chat/WeatherMark.vue')['default']
    WeatherReplyCard: typeof import('./components/chat/WeatherReplyCard.vue')['default']
  }
}
